// React/src/App.tsx
import React, { useCallback, useState, useEffect } from 'react';
import FileManager, { Permissions } from 'devextreme-react/file-manager';
import RemoteFileSystemProvider from 'devextreme/file_management/remote_provider';
import { LoadPanel } from 'devextreme-react/load-panel';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import { PositionConfig } from 'devextreme/animation/position';

const baseUrl = 'https://localhost:7049/api/';
const fileSystemProvider = new RemoteFileSystemProvider({
  endpointUrl: `${baseUrl}file-manager-azure`,
});

const allowedFileExtensions: string[] = [];
const loadPanelPosition: PositionConfig = { of: '#file-manager' };

function App(): JSX.Element {
  const [wrapperClassName, setWrapperClassName] = useState('');
  const [loadPanelVisible, setLoadPanelVisible] = useState(true);
  const checkAzureStatus = useCallback(() => {
    fetch(`${baseUrl}file-manager-azure-status?widgetType=fileManager`)
      .then((response) => {
        if (!response.ok) {
          throw new Error('Network response was not ok');
        }
        return response.json();
      })
      .then((result) => {
        const className = result.active ? 'show-widget' : 'show-message';
        setWrapperClassName(className);
        setLoadPanelVisible(false);
      })
      .catch((error) => {
        /* eslint-disable no-console */
        console.error('Error fetching Azure status:', error);
        /* eslint-enable no-console */
      });
  }, []);

  useEffect(() => {
    checkAzureStatus();
  }, [checkAzureStatus]);

  return (
    <div id="wrapper" className={wrapperClassName}>
      <LoadPanel visible={loadPanelVisible} position={loadPanelPosition} />
      <FileManager id="file-manager" fileSystemProvider={fileSystemProvider} allowedFileExtensions={allowedFileExtensions}>
        {/* uncomment the code below to enable file/directory management */}
        <Permissions
          // create={true}
          // copy={true}
          // move={true}
          // delete={true}
          // rename={true}
          // upload={true}
          download={true}>
        </Permissions>
      </FileManager>
      <div id="message-box">To run the demo, specify your Azure storage account name, access key and container name in the <strong>appsettings.json</strong> file.</div>
    </div>
  );
}

export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { lastValueFrom } from 'rxjs';
import RemoteFileSystemProvider from 'devextreme/file_management/remote_provider';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  preserveWhitespaces: true,
})
export class AppComponent {
  allowedFileExtensions: string[];

  fileSystemProvider: RemoteFileSystemProvider;

  wrapperClassName: string;

  loadPanelVisible: boolean;

  baseUrl = 'https://localhost:7049/api/';

  constructor(http: HttpClient) {
    this.allowedFileExtensions = [];
    this.fileSystemProvider = new RemoteFileSystemProvider({
      endpointUrl: `${this.baseUrl}file-manager-azure`,
    });

    this.wrapperClassName = '';
    this.loadPanelVisible = true;

    this.checkAzureStatus(http);
  }

  checkAzureStatus(http: HttpClient): void {
    const observable = http.get<{ active: boolean }>(`${this.baseUrl}file-manager-azure-status?widgetType=fileManager`);
    const promise = lastValueFrom(observable);

    promise
      .then((response) => {
        this.wrapperClassName = response.active ? 'show-widget' : 'show-message';
        this.loadPanelVisible = false;
      })
      .catch((error) => {
        /* eslint-disable no-console */
        console.error('Error occurred:', error);
        /* eslint-enable no-console */
      });
  }
}

<div id="wrapper" [class]="wrapperClassName">
  <dx-load-panel
    [position]="{ of: '#file-manager' }"
    [(visible)]="loadPanelVisible"
  >
  </dx-load-panel>
  <dx-file-manager
    id="file-manager"
    [fileSystemProvider]="fileSystemProvider"
    [allowedFileExtensions]="allowedFileExtensions"
  >
    <!-- uncomment the code below to enable file/directory management -->
    <!-- <dxo-permissions 
            [create]="true"
            [copy]="true"
            [move]="true"
            [delete]="true"
            [rename]="true"
            [upload]="true"
            [download]="true">
        </dxo-permissions> -->
  </dx-file-manager>
  <div id="message-box">
    To run the demo, specify your Azure storage account name, access key and
    container name in the <strong>appsettings.json</strong> file.
  </div>
</div>
